### ISSUE TITLE
Wrong processing

### ISSUE THREAD

**Issue by pavelzv1211** [zavolokas/Inpainting#17]
Hello! Thanks  for the interesting application.
I executed your app several times ( Inpaint and InpaintWinForms ) and I couldn't get a result like in your screenshot.
The output file is much worse quality than your.
![image](https://user-images.githubusercontent.com/38405840/40449632-b65bb91e-5ee1-11e8-94d0-88d34e50536e.png)
What's wrong?
The last commit I use is `a75d652`
Thank you!

**Comment by zavolokas** [comment]
I've got the result using Inpaint sample with some adjustments of settings (amount of iterations, etc). Inpaint sample saves each intermediate result to the disk with the file name pattern "r{levelIndex}_{IterationIndex}.png" and the best result was the first iteration of the last level.
