### ISSUE TITLE
Create sample REST API project 

### ISSUE THREAD

**Issue by zavolokas** [zavolokas/Inpainting#21]
Sample REST API project that has an endpoint that:
 -  allows to submit input images.
 - starts an inpainting process based on the input
 - returns an inpainted image

**Comment by ektaarora3501** [comment]
hello @zavolokas  can you tell more about this ?

**Comment by zavolokas** [comment]
> hello @zavolokas can you tell more about this ?
Hi @ektaarora3501, the task is to create a simple REST project that runs inpainting. Basically executes the a sample code from [here](https://github.com/zavolokas/Inpainting/tree/master/Samples/Inpaint) in a web environment. 

How to start with creating REST API you can read [here](https://dzone.com/articles/backend-web-api-with-c-step-by-step-tutorial), or [here](https://www.c-sharpcorner.com/article/building-a-restful-api-in-asp-net/)

Hope I answered your question if not - please don't hesitate ask me about details you are interested in ;)

**Comment by ferib** [comment]
Hey @zavolokas 
Been working with the C# Nancy framework lately and this seems something i want to try.
Nancy offers a self-hosted option for a lightweight API, and that seems to be what you need?

**Comment by zavolokas** [comment]
> Hey @zavolokas
> Been working with the C# Nancy framework lately and this seems something i want to try.
> Nancy offers a self-hosted option for a lightweight API, and that seems to be what you need?

Sounds good @ferib ! It would be defiantly interesting to see 😉

**Comment by JEvason90** [comment]
Does the REST api need to store the modified image to the database (or store on disk with the directory saved on a database) or are you merely looking to POST and image to a web end point for manipulation and have it handed back to the client?

**Comment by zavolokas** [comment]
> Does the REST api need to store the modified image to the database (or store on disk with the directory saved on a database) or are you merely looking to POST and image to a web end point for manipulation and have it handed back to the client?

For the sake of the example the later is enough. Get an image, process it, return it back to the client.

**Comment by ferib** [comment]
> > Does the REST api need to store the modified image to the database (or store on disk with the directory saved on a database) or are you merely looking to POST and image to a web end point for manipulation and have it handed back to the client?
> 
> For the sake of the example the later is enough. Get an image, process it, return it back to the client.

Awesome, in my example you send 2 files to the server and the server will return 1 processed image to the client. The Pull Request has been opened already.
