### ISSUE TITLE
Dockerize existing sample project

### ISSUE THREAD

**Issue by zavolokas** [zavolokas/Inpainting#26]
Here is [InpaintHTTP](https://github.com/zavolokas/Inpainting/tree/master/Samples/InpaintHTTP) sample project. 

The task is to create a multistage docker compose/Dockerfile so that it would be possible to build and create an image with the sample application running in a docker container.

[Here ](https://blogs.msdn.microsoft.com/stevelasker/2017/09/11/net-and-multistage-dockerfiles/) and [here](https://github.com/sixeyed/dak4.net/blob/master/docker/prod-logging/signup-web/Dockerfile) is some info to start with

**Comment by Marusyk** [comment]
I will take it

**Comment by Octoate** [comment]
Hi,
I would like to have a look at this if it is okay. Please assign the issue to me.

**Comment by zavolokas** [comment]
> Hi,
> I would like to have a look at this if it is okay. Please assign the issue to me.

Sure, you are very welcome, @Octoate !

**Comment by Octoate** [comment]
Added a Dockerfile in PR #30

**Comment by zavolokas** [comment]
> Added a Dockerfile in PR #30

Great job 👍
Thank you for your effort
