### ISSUE TITLE
Improve a web page design/UX

### ISSUE THREAD

**Issue by zavolokas** [zavolokas/Inpainting#27]
Here is [InpaintHTTP](https://github.com/zavolokas/Inpainting/tree/master/Samples/InpaintHTTP) sample project. 

The task is to come up with a nicer/improved design/UX .

**Comment by ferib** [comment]
i would love to improve some of that in the next couple of days!

**Comment by zavolokas** [comment]
I would suggest to go for simplest possible incremental improvements. 
What that could be?

For example it could be functional improvements:

- After the result image is ready it is displayed on the page rather than gets downloaded
- After the result image is ready you see three images:
   1. original
   2. original + mask overlay
   3. result

Or it can be a layout that looks nicer.
