### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by albingit70** [zavolokas/Inpainting#40]
Hello @zavolokas 
I tried to run docker on my computer(Windows 10) with the command `docker run -p 5000:80 -it --rm zavolokas/inpainter:latest`
But It is failed with the message:
```
docker run -p 5000:80 -it --rm zavolokas/inpainter:latest
Unable to find image 'zavolokas/inpainter:latest' locally
latest: Pulling from zavolokas/inpainter
docker: image operating system "linux" cannot be used on this platform.
See 'docker run --help'.
```

How I can resolve the problem?
Thank you

**Comment by zavolokas** [comment]
@albingit70 here you are https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
