### ISSUE TITLE
Inpainting going outside of donor regions

### ISSUE THREAD

**Issue by tylandercasper** [zavolokas/Inpainting#41]
I'm using your project to generate textures from a 2D image, and I've noticed that a lot of the times it's pulling from regions outside of the donor list. 

Since I'm only passing in the object to fill, this ends up creating shadows from the transparent regions. 
I'm attaching some sample data here: 

BaseImage:
![base](https://user-images.githubusercontent.com/5085108/84831618-e6f04180-afe8-11ea-93e6-5f3553a66f1c.png)
Delete Mask:
![delete](https://user-images.githubusercontent.com/5085108/84831623-e9eb3200-afe8-11ea-87df-859acc560999.png)
Donor Mask:
![donor](https://user-images.githubusercontent.com/5085108/84831628-eb1c5f00-afe8-11ea-83ec-9790b27a94d9.png)

Since the donor area doesn't contain any black, the ultimate result shouldn't contain any either, but it ends up looking like this:
![result](https://user-images.githubusercontent.com/5085108/84832094-d8eef080-afe9-11ea-91ba-29173d7e55bb.png)

**Comment by tylandercasper** [comment]
Also great work! I love how you have it set up to show the progress while it's filling in the regions. 
It's an extremely impressive engine.

**Comment by tylandercasper** [comment]
I'm attaching another sample that gives a better appearance of how it's used. For visual purposes I replaced the white masks with the actual content that's being used for the donars and deletion:

Base image:
![base](https://user-images.githubusercontent.com/5085108/84843429-14e37f00-b005-11ea-98cb-f6ae5ec0cbbb.png)
Delete Mask:
![delete](https://user-images.githubusercontent.com/5085108/84843441-1c0a8d00-b005-11ea-8d8a-99090562af95.png)
Donor Mask:
![donor](https://user-images.githubusercontent.com/5085108/84843453-24fb5e80-b005-11ea-9d41-1b12016bcfe7.png)

Result:
![Result](https://user-images.githubusercontent.com/5085108/84843463-2af13f80-b005-11ea-936d-c2f5e3164387.png)

I can understand if the black spot inbetween the two main floor boards is considered out of scope for what you're intending with the tool, but the blurred black around the edges and the big black spot on the right definitely an indicator that donor's aren't working quite right in general.

**Comment by zavolokas** [comment]
@tylandercasper thanks for the feedback! Currently there is no support for the semitransparent images.

**Comment by tylandercasper** [comment]
Well, even if I fill in the main image so the background is one color instead of clear (which I believe the program already does internally), it'll still draw from whatever the background is even though it's not in the donor region. 

Here's an example with the background filled with pink. If it was exclusively using the donor region than it would then the entire section above would still be visible. Instead the background is used to fill in the center and the sides of the image, 

![pink](https://user-images.githubusercontent.com/5085108/84911937-17ca8800-b076-11ea-99b7-b6c9343420a2.png)

**Comment by zavolokas** [comment]
@tylandercasper I took a closer look at the markups. The essential part about the donor markup is that is should overlap with the area that you want to inpaint. The overlapping area needs to be inpainted using pixels from the part that doesn't overlap. 
Basically what you do that way is you are telling that **this is one thing, but a part of it is missing, please reconstruct the missing part from the part that present**.

Since your donor doesn't overlap with the area to inpaint, the algorithm doesn't know which parts you want to inpaint with these donors, so it uses the whole image.

**Comment by zavolokas** [comment]
Example: 
- red - area to inpaint, 
- blue - area to take pixels from to reconstruct pixels under the both blue and red
- green - area to take pixels from to reconstruct pixels under the both green and red
![image](https://user-images.githubusercontent.com/12433394/85072027-51071300-b1b0-11ea-9674-beaf8ceb92e2.png)

**Comment by tylandercasper** [comment]
I did what you suggested and it looks a LOT better! 

Thanks so much for your help!
